// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication4.Data;

#nullable disable

namespace WebApplication4.Migrations
{
    [DbContext(typeof(ProjDbContext))]
    partial class ProjDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication4.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("WebApplication4.Models.Blood_data", b =>
                {
                    b.Property<int>("b_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("b_Id"));

                    b.Property<int>("b_price")
                        .HasColumnType("int");

                    b.Property<int>("b_quantity")
                        .HasColumnType("int");

                    b.Property<string>("b_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("h_id")
                        .HasColumnType("int");

                    b.HasKey("b_Id");

                    b.ToTable("Bloods");
                });

            modelBuilder.Entity("WebApplication4.Models.City", b =>
                {
                    b.Property<int>("c_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("c_id"));

                    b.Property<string>("c_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("c_id");

                    b.ToTable("City", (string)null);

                    b.HasData(
                        new
                        {
                            c_id = 1,
                            c_name = "Lahore"
                        },
                        new
                        {
                            c_id = 2,
                            c_name = "Faisalabad"
                        });
                });

            modelBuilder.Entity("WebApplication4.Models.Employee", b =>
                {
                    b.Property<int>("e_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("e_Id"));

                    b.Property<string>("e_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("e_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("e_Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("e_centre_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("e_Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("WebApplication4.Models.Hospital", b =>
                {
                    b.Property<int>("h_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("h_Id"));

                    b.Property<int>("h_bloodquantity")
                        .HasColumnType("int");

                    b.Property<string>("h_city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("h_img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("h_loc_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("h_location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("h_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("h_Id");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("WebApplication4.Models.Transaction", b =>
                {
                    b.Property<int?>("t_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("t_Id"));

                    b.Property<int>("b_id")
                        .HasColumnType("int");

                    b.Property<int>("h_id")
                        .HasColumnType("int");

                    b.Property<int>("t_bloodprice")
                        .HasColumnType("int");

                    b.Property<int>("t_bloodquantity")
                        .HasColumnType("int");

                    b.Property<string>("t_bloodtype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("u_id")
                        .HasColumnType("int");

                    b.Property<string>("u_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("t_Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("WebApplication4.Models.User", b =>
                {
                    b.Property<int?>("u_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("u_Id"));

                    b.Property<string>("u_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u_Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u_PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u_bloodgroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("u_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("u_wallet")
                        .HasColumnType("int");

                    b.HasKey("u_Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
